### ISSUE TITLE
any build available  ?

### ISSUE THREAD

**Issue by GeraudBourdin** [spunkedy/irblast#1]
Hi, 
is there any package ready for this module ? 
thanks.

**Comment by spunkedy** [comment]
You can look in the dist folder. Otherwise you can import it into titanium workspace to be able to use it.

**Comment by GeraudBourdin** [comment]
Thank you for your answer. It appears that getSystemService("irda") do not works on my samsung S4, but the getSystemService("consumer_ir") works. 
So i made a simple module for my own use. 
Thanks.

**Comment by spunkedy** [comment]
Wonderful. 
It was written with galaxy tab 3. And it was undocumented.
